### ISSUE TITLE
Mixins may not be defined within control directives or other mixins.

### ISSUE THREAD

**Issue by coreybutler** [ngnjs/chassis-detailer#1]
In the latest version of libsass, the error appears to be due to the `@if` followed by the mixin definitons beginning on [line 68 of _buttons.scss](https://github.com/ngnjs/chassis-detailer/blob/master/detailer/ui-components/_buttons.scss#L68).

``` sh
Message:
    ../node_modules/chassis-detailer/detailer/ui-components/_buttons.scss
Error: Mixins may not be defined within control directives or other mixins.
        on line 68 of ../node_modules/chassis-detailer/detailer/ui-components/_buttons.scss
>>   @mixin button-pseudo-class($type, $settings) {
   --^
```

I suspect this is a problem in the other UI components as well, but this happens to be the first file in the directory (the gulp process chokes after the first error).

**Comment by gbdrummer** [comment]
Fixed with latest release.
